apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens20f0np0",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.109.200-192.168.109.250/24",
        "gateway": "192.168.109.254",
        "routes": [ { "dst": "0.0.0.0/0" } ]
      }
    }'
