apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.1.200-192.168.1.250/24",
        "gateway": "192.168.1.1",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
