apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-macvlan
  namespace: default
spec:
  config: '{"cniVersion": "0.3.1", "type": "macvlan", "master": "enp193s0f0np0", "mode": "bridge", "mtu": 1400, "ipam": {"type": "whereabouts", "range": "192.168.110.110-192.168.110.250/24"}}'
