apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-pod
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: volume-test
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo 'Success! Longhorn is working!' > /data/test.txt && cat /data/test.txt && sleep 3600"]
    volumeMounts:
    - name: test-vol
      mountPath: /data
  volumes:
  - name: test-vol
    persistentVolumeClaim:
      claimName: longhorn-test-pvc
